# 数据路径配置
data:
  real_data_path: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/Data/SAMPLE/real'
  real_data_path_test: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/Data/SAMPLE/real'
  sim_data_path: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/Data/SAMPLE/synth'
  save_dir: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/New_paper/checkpoints/scenario1'
  result_dir: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/New_paper/result_txt/scenario1'

# 训练参数配置
training:
  batch_size: 16
  epochs: 100
  lr: 0.000125
  test_interval: 5
  dropout_rate: 0
  num_repeats: 20  # 重复实验次数
  
# 损失权重配置
weights:
  class_weight: 1.0      # 分类损失权重
  mmd_weight: 0.75       # MMD损失权重
  domain_weight: 0.01   # 域对抗损失权重

#weights:
#  class_weight: 1.0      # 分类损失权重
#  mmd_weight: 0.5       # MMD损失权重
#  domain_weight: 0.015   # 域对抗损失权重
  
# 模型配置
model:
  num_classes: 10
