# 数据路径配置
data:
  real_data_path: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/Data/SAMPLE/real_elev_17'
  real_data_path_test: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/Data/SAMPLE/real_elev_17'
  sim_data_path: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/Data/SAMPLE/synth_elev_14_16'
  save_dir: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/New_paper/checkpoints/scenario2'
  result_dir: '/home/liusir/PycharmProjects/pythonProject/SAMPLE/New_paper/result_txt/scenario2'

# 训练参数配置
training:
  batch_size: 16
  epochs: 100
  lr: 0.001
  test_interval: 5
  dropout_rate: 0.2
  num_repeats: 20  # 重复实验次数

# 模型配置
model:
  num_classes: 10